In [1]:
import numpy as np
import pandas as pd

In [8]:
l = [[10,20,30],[110,20,20,45]]
df = pd.DataFrame(l)
print(df)

     0   1   2     3
0   10  20  30   NaN
1  110  20  20  45.0

In [10]:
# naming the column index
l = [[10,20,30],[110,20,20,45]]
df = pd.DataFrame(l, columns=['sun','mon','tue','wed'])
print(df)

   sun  mon  tue   wed
0   10   20   30   NaN
1  110   20   20  45.0

In [20]:
d = {'a':[1,2,3,4],'b':[10,20,30,40],'c':[100,200,300,400]}
df = pd.DataFrame(d)
df

   a   b    c
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400

In [17]:
d = {'a':1,'b':10,'c':100}
df = pd.DataFrame(d, index=[1])
df

   a   b    c
1  1  10  100

In [22]:
d = pd.read_excel('StudentPerformanceFactors.xlsx')
df = pd.DataFrame(d)
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7.0,79,Low,Yes,0.0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8.0,56,Low,Yes,2.0,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7.0,91,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8.0,98,Medium,Yes,1.0,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6.0,65,Medium,Yes,3.0,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7.0,76,Medium,Yes,1.0,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,NaN,81,Medium,Yes,3.0,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6.0,65,Low,Yes,3.0,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6.0,91,High,Yes,2.0,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9.0,94,Medium,Yes,0.0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [31]:
d = pd.read_csv('cybrom_medical_dataset.csv', usecols= [0,4], nrows= 10)
df = pd.DataFrame(d)
df

  Patient_ID        Department
0      P1001        Pediatrics
1      P1002        Cardiology
2      P1003       Orthopedics
3      P1004               ICU
4      P1005          Oncology
5      P1006           Surgery
6      P1007          Oncology
7      P1008         Radiology
8      P1009  General Medicine
9      P1010        Cardiology

In [68]:
# attributes
d = pd.read_excel('StudentPerformanceFactors.xlsx')
df = pd.DataFrame(d)
# df.shape
# df.dtypes
# df.columns
# df.index
# df.values
# df.head()
# df.tail()
# df.sample()
# df.info()
# df.describe(include= 'all')
# df.isnull()
# df.isnull().sum()
# df.duplicated()
# df.duplicated().sum()
# df.rename(columns= {'Hours_Studied' : 'Total', 'Sleep_Hours':'hours'})
# df.rename(columns= {'Hours_Studied' : 'Total', 'Sleep_Hours':'hours'}, inplace=True)
df

,Total,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7.0,79,Low,Yes,0.0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8.0,56,Low,Yes,2.0,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7.0,91,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8.0,98,Medium,Yes,1.0,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6.0,65,Medium,Yes,3.0,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7.0,76,Medium,Yes,1.0,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,NaN,81,Medium,Yes,3.0,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6.0,65,Low,Yes,3.0,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6.0,91,High,Yes,2.0,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9.0,94,Medium,Yes,0.0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [ ]:
d = pd.read_excel('StudentPerformanceFactors.xlsx')
df = pd.DataFrame(d)
df