In [2]:
import numpy as np
import pandas as pd

In [8]:
l = [[10,20,30],[110,20,20,45]]
df = pd.DataFrame(l)
print(df)

     0   1   2     3
0   10  20  30   NaN
1  110  20  20  45.0

In [10]:
# naming the column index
l = [[10,20,30],[110,20,20,45]]
df = pd.DataFrame(l, columns=['sun','mon','tue','wed'])
print(df)

   sun  mon  tue   wed
0   10   20   30   NaN
1  110   20   20  45.0

In [20]:
d = {'a':[1,2,3,4],'b':[10,20,30,40],'c':[100,200,300,400]}
df = pd.DataFrame(d)
df

   a   b    c
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400

In [17]:
d = {'a':1,'b':10,'c':100}
df = pd.DataFrame(d, index=[1])
df

   a   b    c
1  1  10  100

In [22]:
d = pd.read_excel('StudentPerformanceFactors.xlsx')
df = pd.DataFrame(d)
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7.0,79,Low,Yes,0.0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8.0,56,Low,Yes,2.0,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7.0,91,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8.0,98,Medium,Yes,1.0,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6.0,65,Medium,Yes,3.0,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7.0,76,Medium,Yes,1.0,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,NaN,81,Medium,Yes,3.0,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6.0,65,Low,Yes,3.0,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6.0,91,High,Yes,2.0,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9.0,94,Medium,Yes,0.0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [31]:
d = pd.read_csv('cybrom_medical_dataset.csv', usecols= [0,4], nrows= 10)
df = pd.DataFrame(d)
df

  Patient_ID        Department
0      P1001        Pediatrics
1      P1002        Cardiology
2      P1003       Orthopedics
3      P1004               ICU
4      P1005          Oncology
5      P1006           Surgery
6      P1007          Oncology
7      P1008         Radiology
8      P1009  General Medicine
9      P1010        Cardiology

In [68]:
# attributes
d = pd.read_excel('StudentPerformanceFactors.xlsx')
df = pd.DataFrame(d)
# df.shape
# df.dtypes
# df.columns
# df.index
# df.values
# df.head()
# df.tail()
# df.sample()
# df.info()
# df.describe(include= 'all')
# df.isnull()
# df.isnull().sum()
# df.duplicated()
# df.duplicated().sum()
# df.rename(columns= {'Hours_Studied' : 'Total', 'Sleep_Hours':'hours'})
# df.rename(columns= {'Hours_Studied' : 'Total', 'Sleep_Hours':'hours'}, inplace=True)
df

,Total,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7.0,79,Low,Yes,0.0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8.0,56,Low,Yes,2.0,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7.0,91,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8.0,98,Medium,Yes,1.0,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6.0,65,Medium,Yes,3.0,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7.0,76,Medium,Yes,1.0,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,NaN,81,Medium,Yes,3.0,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6.0,65,Low,Yes,3.0,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6.0,91,High,Yes,2.0,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9.0,94,Medium,Yes,0.0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [2]:
d = pd.read_excel('StudentPerformanceFactors.xlsx')
df = pd.DataFrame(d)
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7.0,79,Low,Yes,0.0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8.0,56,Low,Yes,2.0,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7.0,91,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8.0,98,Medium,Yes,1.0,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6.0,65,Medium,Yes,3.0,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7.0,76,Medium,Yes,1.0,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,NaN,81,Medium,Yes,3.0,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6.0,65,Low,Yes,3.0,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6.0,91,High,Yes,2.0,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9.0,94,Medium,Yes,0.0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [7]:
df = pd.read_csv('dec_reg_tab.csv')
print(df)
print(df['EXP'].sum())

   EXP  GAP  SALARY
0  2.0  YES      40
1  2.5   NO      42
2  3.0   NO      52
3  4.0   NO      60
4  4.5  YES      56
16.0

In [15]:
df = pd.read_csv('dec_reg_tab.csv')
print(df)
s = pd.Series(['A','B','C','D','E'])
df.set_index(s, inplace = True)

   EXP  GAP  SALARY
0  2.0  YES      40
1  2.5   NO      42
2  3.0   NO      52
3  4.0   NO      60
4  4.5  YES      56
   EXP  GAP  SALARY
0  2.0  YES      40
1  2.5   NO      42
2  3.0   NO      52
3  4.0   NO      60
4  4.5  YES      56

In [29]:
df = pd.read_csv('dec_reg_tab.csv')
# print(df)
df['S.N'] = ['A','B','C','D','E']
print(df)
df.set_index('S.N', inplace = True)          #inplace = True, is used for make changes permanent
# print(df['EXP'])
# print(df.head(1))
print(df.loc['A'])
print(df.loc['A':'C'])                 # .loc : used with name (when indexing is defiend
print(df.iloc[0:2])                    # .iloc : used with numeric indexing

   EXP  GAP  SALARY S.N
0  2.0  YES      40   A
1  2.5   NO      42   B
2  3.0   NO      52   C
3  4.0   NO      60   D
4  4.5  YES      56   E
EXP       2.0
GAP       YES
SALARY     40
Name: A, dtype: object
     EXP  GAP  SALARY
S.N
A    2.0  YES      40
B    2.5   NO      42
C    3.0   NO      52
     EXP  GAP  SALARY
S.N
A    2.0  YES      40
B    2.5   NO      42

In [36]:
# astype

print(df)
df['SALARY'] = df['SALARY'].astype(int)
print(df)

     EXP  GAP  SALARY
S.N
A      2  YES    40.0
B      2   NO    42.0
C      3   NO    52.0
D      4   NO    60.0
E      4  YES    56.0
     EXP  GAP  SALARY
S.N
A      2  YES      40
B      2   NO      42
C      3   NO      52
D      4   NO      60
E      4  YES      56

In [40]:
# between
print(df['SALARY'].between(40,52))
print((40,52)])

S.N
A     True
B     True
C     True
D    False
E    False
Name: SALARY, dtype: bool
     EXP  GAP  SALARY
S.N
A      2  YES      40
B      2   NO      42
C      3   NO      52

In [6]:
a = [[1,2],[1,2],[3,4],[5,6],[5,6],[5,6],[2,8],[6,5]]
d = pd.DataFrame(a)
print(d)
print()
print(d.drop_duplicates())
print()
print(d.drop_duplicates(keep='last'))
print()
print(d.drop_duplicates(keep=False))

   0  1
0  1  2
1  1  2
2  3  4
3  5  6
4  5  6
5  5  6
6  2  8
7  6  5

   0  1
0  1  2
2  3  4
3  5  6
6  2  8
7  6  5

   0  1
1  1  2
2  3  4
5  5  6
6  2  8
7  6  5

   0  1
2  3  4
6  2  8
7  6  5

In [3]:
df = pd.read_csv('myrgroup.csv')
df

        day    city weather  temp  windspeed
0  1/1/2024  bhopal     fog  24.0       10.0
1  1/2/2024  indore   sunny  32.0        4.0
2  1/3/2024  bhopal   rainy  20.0       18.0
3  1/4/2024  bhopal     fog  20.0       16.0
4  1/5/2024  indore   sunny  35.0        5.0
5  1/6/2024  bhopal   rainy  21.0       20.0
6  1/7/2024  ujjain   sunny  38.0        3.0
7  1/8/2024  ujjain   rainy  19.0       17.0
8  1/9/2024  ujjain     fog   NaN        NaN

In [6]:
# dropna : drops complete row if it has atleast one none value 
df.dropna()

        day    city weather  temp  windspeed
0  1/1/2024  bhopal     fog  24.0       10.0
1  1/2/2024  indore   sunny  32.0        4.0
2  1/3/2024  bhopal   rainy  20.0       18.0
3  1/4/2024  bhopal     fog  20.0       16.0
4  1/5/2024  indore   sunny  35.0        5.0
5  1/6/2024  bhopal   rainy  21.0       20.0
6  1/7/2024  ujjain   sunny  38.0        3.0
7  1/8/2024  ujjain   rainy  19.0       17.0
8  1/9/2024  ujjain     fog   NaN        NaN

In [8]:
A = [[1,2,3,4,5],[6,7,8,9,0],[None,None,None,None,None]]
a = pd.DataFrame(A)
print(a)
a.dropna(how='all')

     0    1    2    3    4
0  1.0  2.0  3.0  4.0  5.0
1  6.0  7.0  8.0  9.0  0.0
2  NaN  NaN  NaN  NaN  NaN

     0    1    2    3    4
0  1.0  2.0  3.0  4.0  5.0
1  6.0  7.0  8.0  9.0  0.0

In [41]:
# fillna : used to fill a value in every none value in dataframe

A = [[1,2,3,4,5],[6,7,8,9,0],[None,None,None,None,None]]
a = pd.DataFrame(A, columns=['s1','s2','s3','s4','s5'])
# a.fillna(0)         default filling
print(a['s3'].fillna(5))     # filling at a specific position
# a['s3'] = a['s3'].fillna(5)    for permanent change
print(a)
print(a['s4'].fillna(a['s4'].mean()))    # replacing with mean value
a['s5'].ffill()

0    3.0
1    8.0
2    5.0
Name: s3, dtype: float64
    s1   s2   s3   s4   s5
0  1.0  2.0  3.0  4.0  5.0
1  6.0  7.0  8.0  9.0  0.0
2  NaN  NaN  NaN  NaN  NaN
0    4.0
1    9.0
2    6.5
Name: s4, dtype: float64

0    5.0
1    0.0
2    0.0
Name: s5, dtype: float64

In [43]:
A = [[1,2,3,4,5],[6,7,8,9,0],[None,None,None,None,None]]
a = pd.DataFrame(A, columns=['s1','s2','s3','s4','s5'])
a.drop(columns=['s4','s5'])

    s1   s2   s3
0  1.0  2.0  3.0
1  6.0  7.0  8.0
2  NaN  NaN  NaN

In [ ]:
# apply function