In [44]:
import pandas as pd
import numpy as np

In [45]:
data = {
    "Name": ["Vishesh", "Rahul", "Ankit"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)
print(df)

      Name  Age  Marks
0  Vishesh   21     85
1    Rahul   22     90
2    Ankit   20     78

In [46]:
a = [1,2,3,4,5]
print(a, type(a))
k=pd.Series(a)
print(k, type(k))

[1, 2, 3, 4, 5] <class 'list'>
0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.Series'>

In [47]:
a = { 'a':10, 'b':12, 'c':13}
print(a, type(a))
k=pd.Series(a)
print(k, type(k))

{'a': 10, 'b': 12, 'c': 13} <class 'dict'>
a    10
b    12
c    13
dtype: int64 <class 'pandas.Series'>

In [48]:
# attributes of series
a = [1,2,3,4,5]
print(a, type(a))
k=pd.Series(a)
print(k, type(k))
print(k.size)
print(k.dtype)
print(k.name)
print(k.index)
print(k.values)

[1, 2, 3, 4, 5] <class 'list'>
0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.Series'>
5
int64
None
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]

In [49]:
a = [1,2,3,4,5, True]
print(a, type(a))
k=pd.Series(a, name = 'lit')
print(k, type(k))
print(k.dtype)
print(k.name)
print(k.is_unique)

[1, 2, 3, 4, 5, True] <class 'list'>
0       1
1       2
2       3
3       4
4       5
5    True
Name: lit, dtype: object <class 'pandas.Series'>
object
lit
False

In [50]:
a = {'name':['a','b'], 'age':[10,20]}
k=pd.Series(a)
print(k)
print(k['name'][1])

name      [a, b]
age     [10, 20]
dtype: object
b

In [51]:
name = ['phy', 'chem', 'math', 'eng']
score = [76,65,88,96]
s = pd.Series(score, index = name)
print(s)

phy     76
chem    65
math    88
eng     96
dtype: int64

In [52]:
# methods of series

# head() : gives starting values of data (by default 5)
score = [76,65,88,96,45,78,55,34,12,2,42,73,98]
s = pd.Series(score)
print(s.head(5))

0    76
1    65
2    88
3    96
4    45
dtype: int64

In [53]:
# tail() : gives last values of data (by default 5)
score = [76,65,88,96,45,78,55,34,12,2,42,73,98]
s = pd.Series(score)
print(s.tail(2))

11    73
12    98
dtype: int64

In [54]:
# sample() : gives random value from data (by default 1)
score = [76,65,88,96,45,78,55,34,12,2,42,73,98]
s = pd.Series(score)
print(s.sample(5))

4     45
12    98
6     55
1     65
3     96
dtype: int64

In [55]:
score = [76,65,88,96,65,78,65,34,2,2,42,73,98]
s = pd.Series(score)
print(s.value_counts())

65    3
2     2
76    1
88    1
96    1
78    1
34    1
42    1
73    1
98    1
Name: count, dtype: int64

In [60]:
score = [76,65,88,96,45,78,55,34,12,2,42,73,98]
s = pd.Series(score)
print(s.sort_values())

9      2
8     12
7     34
10    42
4     45
6     55
1     65
11    73
0     76
5     78
2     88
3     96
12    98
dtype: int64

In [68]:
s = ['a','p','p','l','e']
a = pd.Series(s)
print(a.sort_values())
print(a.sort_values(ascending=False))

0    a
4    e
3    l
1    p
2    p
dtype: str
1    p
2    p
3    l
4    e
0    a
dtype: str

In [77]:
dt = pd.read_csv("cybrom_medical_dataset.csv")
dt

,Patient_ID,Date,Age,Gender,Department,Doctor_Name,Treatment_Type,Patient_Status,Days_Admitted,Treatment_Cost,Insurance_Covered,Bed_Type,Diagnosis
0,P1001,2025-08-01 00:00:00.000000000,56,Male,Pediatrics,Dr. Amit Patel,Rehabilitation,Recovery,20,41783.92,No,Semi-Private,Diabetes
1,P1002,2025-08-02 22:03:38.181818181,19,Female,Cardiology,Dr. Arjun Desai,Emergency Care,Critical,16,63754.30,Yes,General,Migraine
2,P1003,2025-08-04 20:07:16.363636363,76,Female,Orthopedics,Dr. Amit Patel,Diagnostics,Recovery,25,87863.59,Yes,General,Diabetes
3,P1004,2025-08-06 18:10:54.545454545,65,Female,ICU,Dr. Arjun Desai,Emergency Care,Discharged,22,112441.21,Partial,Semi-Private,Fever
4,P1005,2025-08-08 16:14:32.727272727,25,Male,Oncology,Dr. Priya Sharma,Surgery,Discharged,13,116243.25,No,Private,Hypertension
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,P1096,2026-01-30 07:45:27.272727272,37,Male,Oncology,Dr. Sanjay Bhat,Rehabilitation,Under Treatment,10,49627.70,No,Semi-Private,Fracture
96,P1097,2026-02-01 05:49:05.454545454,9,Female,General Medicine,Dr. Anjali Verma,Consultation,Admitted,26,123375.93,Partial,General,Fever
97,P1098,2026-02-03 03:52:43.636363636,45,Female,Surgery,Dr. Amit Patel,Emergency Care,Stable,19,145356.20,No,ICU,Fever
98,P1099,2026-02-05 01:56:21.818181818,32,Male,Oncology,Dr. Arjun Desai,Emergency Care,Admitted,7,17819.19,No,Semi-Private,COVID-19
99,P1100,2026-02-07 00:00:00.000000000,11,Male,General Medicine,Dr. Meera Chopra,Emergency Care,Admitted,3,119813.59,No,Private,Heart Disease

In [85]:
dt.sort_index(axis=1)

,Age,Bed_Type,Date,Days_Admitted,Department,Diagnosis,Doctor_Name,Gender,Insurance_Covered,Patient_ID,Patient_Status,Treatment_Cost,Treatment_Type
0,56,Semi-Private,2025-08-01 00:00:00.000000000,20,Pediatrics,Diabetes,Dr. Amit Patel,Male,No,P1001,Recovery,41783.92,Rehabilitation
1,19,General,2025-08-02 22:03:38.181818181,16,Cardiology,Migraine,Dr. Arjun Desai,Female,Yes,P1002,Critical,63754.30,Emergency Care
2,76,General,2025-08-04 20:07:16.363636363,25,Orthopedics,Diabetes,Dr. Amit Patel,Female,Yes,P1003,Recovery,87863.59,Diagnostics
3,65,Semi-Private,2025-08-06 18:10:54.545454545,22,ICU,Fever,Dr. Arjun Desai,Female,Partial,P1004,Discharged,112441.21,Emergency Care
4,25,Private,2025-08-08 16:14:32.727272727,13,Oncology,Hypertension,Dr. Priya Sharma,Male,No,P1005,Discharged,116243.25,Surgery
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,37,Semi-Private,2026-01-30 07:45:27.272727272,10,Oncology,Fracture,Dr. Sanjay Bhat,Male,No,P1096,Under Treatment,49627.70,Rehabilitation
96,9,General,2026-02-01 05:49:05.454545454,26,General Medicine,Fever,Dr. Anjali Verma,Female,Partial,P1097,Admitted,123375.93,Consultation
97,45,ICU,2026-02-03 03:52:43.636363636,19,Surgery,Fever,Dr. Amit Patel,Female,No,P1098,Stable,145356.20,Emergency Care
98,32,Semi-Private,2026-02-05 01:56:21.818181818,7,Oncology,COVID-19,Dr. Arjun Desai,Male,No,P1099,Admitted,17819.19,Emergency Care
99,11,Private,2026-02-07 00:00:00.000000000,3,General Medicine,Heart Disease,Dr. Meera Chopra,Male,No,P1100,Admitted,119813.59,Emergency Care

In [81]:
# method channing : using multiple methods in one line of code

score = [76,65,88,96,45,78,55,34,12,2,42,73,98]
s = pd.Series(score)
print(s.sort_values().tail())

0     76
5     78
2     88
3     96
12    98
dtype: int64

In [88]:
# mathematical functions
score = [76,65,88,96,65,78,65,34,2,2,42,73,98, None]
s = pd.Series(score)
print(s.count())
print(s.size)

13
14

In [97]:
score = [76,65,88,96,65,78,65,34,2,2,42,73,98]
# score1 = [10,10,10,10,10,10,10,10,10,10,10,10,10]
s = pd.Series(score)
# s1 = pd.Series(score1)
print(s.product())
# print(s*s1)

8601545857364459520
0     760
1     650
2     880
3     960
4     650
5     780
6     650
7     340
8      20
9      20
10    420
11    730
12    980
dtype: int64