In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name": ["Vishesh", "Rahul", "Ankit"],
    "Age": [21, 22, 20],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)
print(df)

      Name  Age  Marks
0  Vishesh   21     85
1    Rahul   22     90
2    Ankit   20     78

In [3]:
a = [1,2,3,4,5]
print(a, type(a))
k=pd.Series(a)
print(k, type(k))

[1, 2, 3, 4, 5] <class 'list'>
0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.Series'>

In [4]:
a = { 'a':10, 'b':12, 'c':13}
print(a, type(a))
k=pd.Series(a)
print(k, type(k))

{'a': 10, 'b': 12, 'c': 13} <class 'dict'>
a    10
b    12
c    13
dtype: int64 <class 'pandas.Series'>

In [5]:
# attributes of series
a = [1,2,3,4,5]
print(a, type(a))
k=pd.Series(a)
print(k, type(k))
print(k.size)
print(k.dtype)
print(k.name)
print(k.index)
print(k.values)

[1, 2, 3, 4, 5] <class 'list'>
0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.Series'>
5
int64
None
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]

In [6]:
a = [1,2,3,4,5, True]
print(a, type(a))
k=pd.Series(a, name = 'lit')
print(k, type(k))
print(k.dtype)
print(k.name)
print(k.is_unique)

[1, 2, 3, 4, 5, True] <class 'list'>
0       1
1       2
2       3
3       4
4       5
5    True
Name: lit, dtype: object <class 'pandas.Series'>
object
lit
False

In [7]:
a = {'name':['a','b'], 'age':[10,20]}
k=pd.Series(a)
print(k)
print(k['name'][1])

name      [a, b]
age     [10, 20]
dtype: object
b

In [8]:
name = ['phy', 'chem', 'math', 'eng']
score = [76,65,88,96]
s = pd.Series(score, index = name)
print(s)

phy     76
chem    65
math    88
eng     96
dtype: int64

In [9]:
# methods of series

# head() : gives starting values of data (by default 5)
score = [76,65,88,96,45,78,55,34,12,2,42,73,98]
s = pd.Series(score)
print(s.head(5))

0    76
1    65
2    88
3    96
4    45
dtype: int64

In [10]:
# tail() : gives last values of data (by default 5)
score = [76,65,88,96,45,78,55,34,12,2,42,73,98]
s = pd.Series(score)
print(s.tail(2))

11    73
12    98
dtype: int64

In [11]:
# sample() : gives random value from data (by default 1)
score = [76,65,88,96,45,78,55,34,12,2,42,73,98]
s = pd.Series(score)
print(s.sample(5))

5    78
3    96
2    88
1    65
6    55
dtype: int64

In [12]:
score = [76,65,88,96,65,78,65,34,2,2,42,73,98]
s = pd.Series(score)
print(s.value_counts())

65    3
2     2
76    1
88    1
96    1
78    1
34    1
42    1
73    1
98    1
Name: count, dtype: int64

In [13]:
score = [76,65,88,96,45,78,55,34,12,2,42,73,98]
s = pd.Series(score)
print(s.sort_values())

9      2
8     12
7     34
10    42
4     45
6     55
1     65
11    73
0     76
5     78
2     88
3     96
12    98
dtype: int64

In [14]:
s = ['a','p','p','l','e']
a = pd.Series(s)
print(a.sort_values())
print(a.sort_values(ascending=False))

0    a
4    e
3    l
1    p
2    p
dtype: str
1    p
2    p
3    l
4    e
0    a
dtype: str

In [15]:
dt = pd.read_csv("cybrom_medical_dataset.csv")
dt.describe()

              Age  Days_Admitted  Treatment_Cost
count  100.000000     100.000000      100.000000
mean    43.110000      15.440000    73518.732300
std     24.295693       8.085802    42778.484212
min      5.000000       1.000000     6982.430000
25%     19.000000       8.750000    39827.585000
50%     45.000000      15.000000    65022.325000
75%     64.000000      22.000000   113105.230000
max     84.000000      29.000000   149395.550000

In [16]:
dt.sort_index(axis=1)

,Age,Bed_Type,Date,Days_Admitted,Department,Diagnosis,Doctor_Name,Gender,Insurance_Covered,Patient_ID,Patient_Status,Treatment_Cost,Treatment_Type
0,56,Semi-Private,2025-08-01 00:00:00.000000000,20,Pediatrics,Diabetes,Dr. Amit Patel,Male,No,P1001,Recovery,41783.92,Rehabilitation
1,19,General,2025-08-02 22:03:38.181818181,16,Cardiology,Migraine,Dr. Arjun Desai,Female,Yes,P1002,Critical,63754.30,Emergency Care
2,76,General,2025-08-04 20:07:16.363636363,25,Orthopedics,Diabetes,Dr. Amit Patel,Female,Yes,P1003,Recovery,87863.59,Diagnostics
3,65,Semi-Private,2025-08-06 18:10:54.545454545,22,ICU,Fever,Dr. Arjun Desai,Female,Partial,P1004,Discharged,112441.21,Emergency Care
4,25,Private,2025-08-08 16:14:32.727272727,13,Oncology,Hypertension,Dr. Priya Sharma,Male,No,P1005,Discharged,116243.25,Surgery
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,37,Semi-Private,2026-01-30 07:45:27.272727272,10,Oncology,Fracture,Dr. Sanjay Bhat,Male,No,P1096,Under Treatment,49627.70,Rehabilitation
96,9,General,2026-02-01 05:49:05.454545454,26,General Medicine,Fever,Dr. Anjali Verma,Female,Partial,P1097,Admitted,123375.93,Consultation
97,45,ICU,2026-02-03 03:52:43.636363636,19,Surgery,Fever,Dr. Amit Patel,Female,No,P1098,Stable,145356.20,Emergency Care
98,32,Semi-Private,2026-02-05 01:56:21.818181818,7,Oncology,COVID-19,Dr. Arjun Desai,Male,No,P1099,Admitted,17819.19,Emergency Care
99,11,Private,2026-02-07 00:00:00.000000000,3,General Medicine,Heart Disease,Dr. Meera Chopra,Male,No,P1100,Admitted,119813.59,Emergency Care

In [17]:
# method channing : using multiple methods in one line of code

score = [76,65,88,96,45,78,55,34,12,2,42,73,98]
s = pd.Series(score)
print(s.sort_values().tail())

0     76
5     78
2     88
3     96
12    98
dtype: int64

In [18]:
# mathematical functions
score = [76,65,88,96,65,78,65,34,2,2,42,73,98, None]
s = pd.Series(score)
print(s.count())
print(s.size)

13
14

In [19]:
score = [76,65,88,96,65,78,65,34,2,2,42,73,98]
# score1 = [10,10,10,10,10,10,10,10,10,10,10,10,10]
s = pd.Series(score)
# s1 = pd.Series(score1)
print(s.product())
# print(s*s1)

8601545857364459520

In [20]:
# describe : returns statsical values for the series
score = [76,65,88,96,65,78,65,34,2,2,42,73,98]
s = pd.Series(score)
print(s.describe())

count    13.000000
mean     60.307692
std      31.721141
min       2.000000
25%      42.000000
50%      65.000000
75%      78.000000
max      98.000000
dtype: float64

In [21]:
# indexing in series
# fancy index [[]] : used when needed to get values in random order
a = [10,4,2,5,6,7]
s = pd.Series(a)
s[[0,3,4]]
print(s)

0    10
1     4
2     2
3     5
4     6
5     7
dtype: int64

In [22]:
# null variation
score = [76,np.nan,88,96,None,78,65,34,None,2,42,73,98]
s = pd.Series(score)
# print(s)
# .isnull() : gives true at positions where value is null
print(s.isnull())
# .hasnans : gives true if there's none value in series
print(s.hasnans)
# .notnull : gives true at positions where value is not null
print(s.notnull())

0     False
1      True
2     False
3     False
4      True
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
dtype: bool
True
0      True
1     False
2      True
3      True
4     False
5      True
6      True
7      True
8     False
9      True
10     True
11     True
12     True
dtype: bool

In [23]:
score = [76,np.nan,88,96,None,78,65,34,None,2,42,73,98]
s = pd.Series(score)
print(s.isnull().sum())

3

In [24]:
score = [76,65,88,96,65,78,65,34,2,2,42,73,98,None]
s = pd.Series(score)
print(s.unique())
print(s.nunique())
print(s.count())

[76. 65. 88. 96. 78. 34.  2. 42. 73. 98. nan]
10
13

In [25]:
score = [76,65,88,96,65,78,65,34,2,2,42,73,98,None]
s = pd.Series(score)
print(len(s))
print(type(s))
# print(dir(s))

14
<class 'pandas.Series'>

In [26]:
# type casting 
score = [76,65,88,96,65,78,65,34,2,2,42,73,98]
s = pd.Series(score)
print(s)
t = tuple(s)
print(t)

0     76
1     65
2     88
3     96
4     65
5     78
6     65
7     34
8      2
9      2
10    42
11    73
12    98
dtype: int64
(76, 65, 88, 96, 65, 78, 65, 34, 2, 2, 42, 73, 98)

In [30]:
# membership operator : seraches index

s = pd.Series([10,215,54,21,65423,11,2,223,44])
print(s)
print(10 in s)

0       10
1      215
2       54
3       21
4    65423
5       11
6        2
7      223
8       44
dtype: int64
False

In [33]:
s = pd.Series([10,215,54,21,65423,11,2,223,44])
print(s)
print(145 in s.values)

0       10
1      215
2       54
3       21
4    65423
5       11
6        2
7      223
8       44
dtype: int64
False

In [34]:
# looping 
s = pd.Series([10,215,54,21,65423,11,2,223,44])
print(s)
for i in s:
    print(i)

0       10
1      215
2       54
3       21
4    65423
5       11
6        2
7      223
8       44
dtype: int64
10
215
54
21
65423
11
2
223
44

In [37]:
s = pd.Series([10,215,54,21,65423,11,2,223,44])
print(s)
for i in range(len(s)):
    s[i] = s[i] + 10
print(s)

0       10
1      215
2       54
3       21
4    65423
5       11
6        2
7      223
8       44
dtype: int64
0       20
1      225
2       64
3       31
4    65433
5       21
6       12
7      233
8       54
dtype: int64

In [39]:
# arthematic operator

# Broadcasting addition
s = pd.Series([10,215,54,21,65423,11,2,223,44])
print(s)
s = s + 10
print(s)
s = s - 10
print(s)

0       10
1      215
2       54
3       21
4    65423
5       11
6        2
7      223
8       44
dtype: int64
0       20
1      225
2       64
3       31
4    65433
5       21
6       12
7      233
8       54
dtype: int64
0       10
1      215
2       54
3       21
4    65423
5       11
6        2
7      223
8       44
dtype: int64

In [46]:
s = pd.Series([10,215,54,21,65423,11,2,223,44])
for i in s:
    if i>15:
        print(i)
print()
print(s[s>15])
print()
print(s)

215
54
21
65423
223
44

1      215
2       54
3       21
4    65423
7      223
8       44
dtype: int64

0       10
1      215
2       54
3       21
4    65423
5       11
6        2
7      223
8       44
dtype: int64

In [49]:
s = pd.Series([10,215,54,21,65423,11,2,223,44])
s.plot(kind = 'Pie')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.